name: Build-Development

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

env:
  AZURE_ARTIFACTS_FEED_URL: https://nuget.pkg.github.com/dominikus1993/index.json
  DOTNET_NOLOGO: true
  USERNAME: dominikus1993

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    # Build
    - run: dotnet nuget add source --username $USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github $AZURE_ARTIFACTS_FEED_URL
    - run: dotnet restore
    - run: dotnet build -c Release

    # Run Unit tests
    - run: dotnet test -c Release --no-build --logger trx --results-directory $GITHUB_WORKSPACE/artifacts

    # Packaging
    - name: dotnet pack Cocona
      run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./src/Cocona/Cocona.csproj
    - name: dotnet pack Cocona.Core
      run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./src/Cocona.Core/Cocona.Core.csproj
    - name: dotnet pack Cocona.Lite
      run: dotnet pack -c Release --no-build --version-suffix "$(versionSuffix)" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./src/Cocona.Lite/Cocona.Lite.csproj

    # Upload & Publish
    - uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: artifacts

    - name: Publish NuGet packages to Azure Artifacts
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        dotnet nuget push --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" $GITHUB_WORKSPACE/artifacts/*.nupkg 
        dotnet nuget push --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" $GITHUB_WORKSPACE/artifacts/*.snupkg
